FROM heroiclabs/nakama:3.22.0

COPY ./build /nakama/data/modules

ENTRYPOINT ["/bin/sh", "-ecx"]
CMD ["\
    /nakama/nakama migrate up --database.address $DB_ADDRESS && \
    exec /nakama/nakama \
    --name nakama1 \
    --database.address $DB_ADDRESS \
    --logger.level DEBUG \
    --session.token_expiry_sec 7200 \
    --runtime.path /nakama/data/modules \
    "]